### PR TITLE
xDnsServer: Add Missing Helper Module Unit Tests

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR adds unit tests for the following `Helper.psm1` functions:

- Get-LocalizedData
- New-TerminatingError
- Assert-Module

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/112)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Cheers Chris, that's great.

**Comment by X-Guardian** [comment]
Can someone review this PR? Thanks.

**Comment by X-Guardian** [comment]
Hi @PlagueHO, are you able to review this PR too? It is a simple one. I just copied the missing common unit tests from the ActiveDirectoryDsc repo.

**Comment by johlju** [comment]
Merging this as it is needed for issue #120

**Pull request merged**
