### PR TITLE
xDnsServerADZone: bugfix #79

### LINKED ISSUE #79: xDnsServerADZone: Cannot call resource from remote server
#### Details of the scenario you tried and the problem that is occurring
Scenario: Adding a new DNS zone to a **remote** DNS server.
 
#### Verbose logs showing the problem
Fails on cimsession. Just took the Get-TargetResource function to dive-in to the source of the problem.

```PowerShell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\...> function Get-TargetResource
>> {
>>     [CmdletBinding()]
>>     [OutputType([System.Collections.Hashtable])]
>>     param
>>     (
>>         [Parameter(Mandatory = $true)]
>>         [ValidateNotNullOrEmpty()]
>>         [System.String]
>>         $Name,
>>
>>         [Parameter()]
>>         [ValidateSet('None','NonsecureAndSecure','Secure')]
>>         [System.String]
>>         $DynamicUpdate = 'Secure',
>>
>>         [Parameter(Mandatory = $true)]
>>         [ValidateSet('Custom','Domain','Forest','Legacy')]
>>         [System.String]
>>         $ReplicationScope,
>>
>>         [Parameter()]
>>         [System.String]
>>         $DirectoryPartitionName,
>>
>>         [Parameter()]
>>         [System.String]
>>         $ComputerName,
>>
>>         [Parameter()]
>>         [pscredential]
>>         $Credential,
>>
>>         [Parameter()]
>>         [ValidateSet('Present','Absent')]
>>         [System.String]
>>         $Ensure = 'Present'
>>     )
>>     #Assert-Module -Name 'DNSServer'
>>     Write-Verbose ($LocalizedData.CheckingZoneMessage -f $Name, $Ensure)
>>
>>     if (!$PSBoundParameters.ContainsKey('ComputerName') -and $PSBoundParameters.ContainsKey('Credential'))
>>     {
>>         throw $LocalizedData.CredentialRequiresComputerNameMessage
>>     }
>>
>>     $getParams = @{
>>         Name = $Name
>>         ErrorAction = 'SilentlyContinue'
>>     }
>>
>>     if ($PSBoundParameters.ContainsKey('ComputerName'))
>>     {
>>         $cimSessionParams = @{
>>             ErrorAction = 'SilentlyContinue'
>>             ComputerName = $ComputerName
>>         }
>>         if ($PSBoundParameters.ContainsKey('Credential'))
>>         {
>>             $cimSessionParams += @{
>>                 Credential = $Credential
>>             }
>>         }
>>         $getParams = @{
>>             CimSession = New-CimSession @cimSessionParams
>>         }
>>     }
>>
>>     $dnsServerZone = Get-DnsServerZone @getParams
>>     if ($getParams.CimSession)
>>     {
>>         Remove-CimSession -CimSession $getParams.CimSession
>>     }
>>     $targetResource = @{
>>         Name = $dnsServerZone.ZoneName
>>         DynamicUpdate = $dnsServerZone.DynamicUpdate
>>         ReplicationScope = $dnsServerZone.ReplicationScope
>>         DirectoryPartitionName = $dnsServerZone.DirectoryPartitionName
>>         Ensure = if ($null -eq $dnsServerZone) { 'Absent' } else { 'Present' }
>>     }
>>     return $targetResource
>> } #end function Get-TargetResource

PS C:\Users\...> get-TargetResource -Name 'jandoedel.iton.nl' -ReplicationScope Forest -ComputerName 'tst-dc1'
-Credential (Get-Credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Get-DnsServerZone : Cannot validate argument on parameter 'CimSession'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At line:69 char:40
+     $dnsServerZone = Get-DnsServerZone @getParams
+                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-DnsServerZone], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-DnsServerZone


Name                           Value
----                           -----
DirectoryPartitionName
DynamicUpdate
Name
ReplicationScope
Ensure                         Absent


PS C:\Users\...> function Get-TargetResource
>> {
>>     [CmdletBinding()]
>>     [OutputType([System.Collections.Hashtable])]
>>     param
>>     (
>>         [Parameter(Mandatory = $true)]
>>         [ValidateNotNullOrEmpty()]
>>         [System.String]
>>         $Name,
>>
>>         [Parameter()]
>>         [ValidateSet('None','NonsecureAndSecure','Secure')]
>>         [System.String]
>>         $DynamicUpdate = 'Secure',
>>
>>         [Parameter(Mandatory = $true)]
>>         [ValidateSet('Custom','Domain','Forest','Legacy')]
>>         [System.String]
>>         $ReplicationScope,
>>
>>         [Parameter()]
>>         [System.String]
>>         $DirectoryPartitionName,
>>
>>         [Parameter()]
>>         [System.String]
>>         $ComputerName,
>>
>>         [Parameter()]
>>         [pscredential]
>>         $Credential,
>>
>>         [Parameter()]
>>         [ValidateSet('Present','Absent')]
>>         [System.String]
>>         $Ensure = 'Present'
>>     )
>>     #Assert-Module -Name 'DNSServer'
>>     Write-Verbose ($LocalizedData.CheckingZoneMessage -f $Name, $Ensure)
>>
>>     if (!$PSBoundParameters.ContainsKey('ComputerName') -and $PSBoundParameters.ContainsKey('Credential'))
>>     {
>>         throw $LocalizedData.CredentialRequiresComputerNameMessage
>>     }
>>
>>     $getParams = @{
>>         Name = $Name
>>         ErrorAction = 'SilentlyContinue'
>>     }
>>
>>     if ($PSBoundParameters.ContainsKey('ComputerName'))
>>     {
>>         $cimSessionParams = @{
>>             ErrorAction = 'SilentlyContinue'
>>             ComputerName = $ComputerName
>>         }
>>         if ($PSBoundParameters.ContainsKey('Credential'))
>>         {
>>             $cimSessionParams += @{
>>                 Credential = $Credential
>>             }
>>         }
>>         $getParams = @{
>>             CimSession = New-CimSession @cimSessionParams
>>         }
>>         $CimSession = New-CimSession @cimSessionParams
>>     }
>>
>>     $dnsServerZone = Get-DnsServerZone -CimSession $CimSession
>>     if ($getParams.CimSession)
>>     {
>>         Remove-CimSession -CimSession $getParams.CimSession
>>     }
>>     $targetResource = @{
>>         Name = $dnsServerZone.ZoneName
>>         DynamicUpdate = $dnsServerZone.DynamicUpdate
>>         ReplicationScope = $dnsServerZone.ReplicationScope
>>         DirectoryPartitionName = $dnsServerZone.DirectoryPartitionName
>>         Ensure = if ($null -eq $dnsServerZone) { 'Absent' } else { 'Present' }
>>     }
>>     return $targetResource
>> } #end function Get-TargetResource

PS C:\Users\...> get-TargetResource -Name 'jandoedel.iton.nl' -ReplicationScope Forest -ComputerName 'tst3-dc1' -Credential (Get-Credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential

Name                           Value
----                           -----
DirectoryPartitionName         {ForestDnsZones.tst.local, $null, $null, DomainDnsZones.tst.local...}
DynamicUpdate                  {Secure, None, None, Secure...}
Name                           {_msdcs.tst.local, 0.in-addr.arpa, 127.in-addr.arpa, 2.0.10.in-addr.arpa...}
ReplicationScope               {Forest, None, None, Domain...}
Ensure                         Present
```

**To be clear; in second function, lines that matter:**
$CimSession = New-CimSession @cimSessionParams
$dnsServerZone = Get-DnsServerZone -CimSession $CimSession

#### Suggested solution to the issue
Force interpretation of the New-CimSession command first;

```PowerShell
>>         $getParams = @{
>>             CimSession = New-CimSession @cimSessionParams
>>         }
```

```PowerShell
Should be:

>>         $getParams = @{
>>             CimSession = (New-CimSession @cimSessionParams)
>>         }
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
**almost template/example**
running on machine X (domain member etc etc), targeting tst3-dc1 (DNS/DC)

```powershell
configuration Sample_xDnsServerForwardADZone
{
    param
    (
        [pscredential]$Credential
    )
    Import-DscResource -module xDnsServer
    node localhost{
        xDnsServerADZone addForwardADZone
        {
            Name = 'MyDomainName.com'
            #DynamicUpdate = 'Secure'
            ReplicationScope = 'Forest'
            ComputerName = 'tst3-dc1'
            Credential = $Credential
            Ensure = 'Present'
        }
    }
}

$MOFPath = 'C:\Support\MOF'
$Credential = Get-credential
If (!(Test-Path -Path $MOFPath)){
    New-Item -Path $MOFPath -ItemType Directory
} Else {
    Remove-Item -Path "$($MOFPath)\*" -Force
}

$cd = @{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            PSDscAllowDomainUser = $true
            PSDscAllowPlainTextPassword = $true
        }
    )
}

Sample_xDnsServerForwardADZone -OutputPath $MOFPath -Credential $Credential -ConfigurationData $cd
Start-DscConfiguration -Path $MOFPath -Wait -Force -verbose
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2430.amd64fre.rs1_release_inmarket_aim.180806-1810
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

(Azure template VM)

#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.14393.2430
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2430
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
PS C:\Users\...> get-package xdnsserver

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
xDnsServer                     1.11.0.0         https://psgallery.office-conn... PowerShellGet

### PR DESCRIPTION
**Pull request by peppekerstens**
#### Pull Request (PR) description

* Fixes bug #79 with proposed solution. 
* Tidy-up of xDnsServer.ps1 ReleasNotes section to improve readability
* Removed references to foreign issues

#### This Pull Request (PR) fixes the following issues

* Fixes #79 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdnsserver/80)

### CODE REVIEW

**Comment by peppekerstens** [comment]
Please do not merge yet...there are more errors. Will update soon...

**Comment by peppekerstens** [comment]
Still very a bad response when wrong/typo in username/password:

```Powershell
annot validate argument on parameter 'CimSession'. The argument is null or empty. Provide an argument that is not null or 
empty, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-DnsServerZone
    + PSComputerName        : localhost
```

But besides that, all fixed now. Now you can create a new zone remotely...

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/80#-:-MTQzJqG5HcKJV3pnyVP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@peppekerstens I took this one over the finish line. Thank you for your contribution and fixing the fix for this issue! 🙂

**Pull request merged**
