### PR TITLE
DnsRecordMx: Implemented as a class-based resource

### LINKED ISSUE #140: DnsRecordMx: Add additional properties
### Description

In line with #34, a DSCResource for MX records should be created. For consistency, the resource should be named `xDnsRecordMx`.

#### Mandatory

- ZoneName: Specifies the name of a DNS zone.
- Name: Specifies the name of a DNS server resource record object.
- MailExchange: Specifies the FQDN of the host that is acting as a mail exchanger for the owner.
- Preference: Specifies the priority for this resource record among other resource records that belong to the same owner, where a lower value has a higher priority.

#### Optional

- AgeRecord: Indicates that the DNS server uses a time stamp for the resource record that this cmdlet adds. A DNS server can scavenge resource records that have become stale based on a time stamp.
- AllowUpdateAny: Indicates that any authenticated user can update a resource record that has the same owner name.
- DnsServer: Specifies a DNS server. If you do not specify this parameter, the command runs on the local system. You can specify an IP address or any value that resolves to an IP address, such as a fully qualified domain name (FQDN), host name, or NETBIOS name.
- TTL: Specifies the Time to Live (TTL) value, in seconds, for a resource record. Other DNS servers use this length of time to determine how long to cache a record.
- ZoneScope: Specifies the name of a zone scope.
- Ensure: Denotes whether the record should be `Present` or `Absent`

### Special considerations or limitations

Not all mandatory properties need to be key properties. Please review the syntax and purpose of this record type to make the best determination of which properties should be key properties.

All proposed properties above options come straight from the `Add-DnsServerResourceRecord` help syntax with two exceptions:

- `TimeToLive` has been changed to `TTL`
- `ComputerName` has been changed to `DnsServer`

### LINKED ISSUE #204: xDnsRecordMx: Unit test missing Mock
#### Details of the scenario you tried and the problem that is occurring

Cannot throw Get-DnsServerResourceRecord Stub call, as it seems one of the MSFT_xDnsRecordMx\Set-TargetResource tests may not have mocked it.

#### Verbose logs showing the problem

```
...
  Describing MSFT_xDnsRecordMx\Set-TargetResource

    Context When managing MX type DNS record
      [-] Calls Add-DnsServerResourceRecord in the set method when Ensure is Present 98ms
        RuntimeException: Get-DnsServerResourceRecord: StubNotImplemented
        at Get-DnsServerResourceRecord, C:\Users\james\Documents\code\xDnsServer\tests\Unit\Stubs\DnsServer.psm1: line 5662
        at Set-TargetResource, C:\Users\james\Documents\code\xDnsServer\output\xDnsServer\0.0.1\DSCResources\MSFT_xDnsRecordMx\MSFT_xDnsRecordMx.psm1: line 163
        at <ScriptBlock>, C:\Users\james\Documents\code\xDnsServer\tests\Unit\MSFT_xDnsRecordMx.Tests.ps1: line 156
VERBOSE: Updating DNS record 'MX' for target 'mail.contoso.com.' in zone 'contoso.com' on 'localhost'.
...
```

#### Suggested solution to the issue

Verify that a mock for Get-DnsServerResourceRecord exists within the scope of the test (prior to being called) at line 156

### PR DESCRIPTION
**Pull request by Sudman1**
#### Pull Request (PR) description

Implements a class-based solution for managing MX records - to include implementation of managing scoped records.

> Note: This PR also removes xDnsRecordMX to avoid conflicts.

#### This Pull Request (PR) fixes the following issues

- Fixes #140

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help. **Does not use schema.mof file. Parameter Descriptions not updated in the README.md, as that has moved to the Wiki.**
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/227)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 20 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/227)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @Sudman1)

___
*[CHANGELOG.md, line 158 at r1](https://reviewable.io/reviews/dsccommunity/xdnsserver/227#-MWiN5ps4YkLy--rZwWf:-MWiN5ps4YkLy--rZwWg:b5q7nes) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/9330d4d5a38224e8429a4283a0b4e4b6b95111fb/CHANGELOG.md#L158)):*
> ```
> - xDnsRecordMx
>   - Replaced with class-based implementation, DnsRecordMx
> ```

Can we revert the removal of the old resource and instead add a deprecated message under `### Deprecated`. Let's remove the old one in the next release (as DnsServerDsc). I will create an issue to track the removal.

**Note! You just need to revert the resource code in `xDnsRecord` folder. Let's delete the examples, unit- and integration tests in this PR.**

**Comment by johlju** [comment]
@Sudman1 I saw you reused the examples, integration tests and unit tests, let's leave them as is. Just revert the code folder `xDnsRecordMx` and add a deprecated message in the change log.

**Comment by johlju** [comment]
Trcking the removal of the old resource here https://github.com/dsccommunity/xDnsServer/issues/228.

**Comment by johlju** [comment]
@Sudman1 seems it fails on the xDnsRecordMx unit test. You can just delete that unit test. There are no changes introduced in this PR that changes that resource, right?

**Comment by johlju** [comment]
...also the integration test for xDnsRecordMx can be removed... it also fails.

**Comment by Sudman1** [comment]
That's correct. Thanks - you've saved me some Pester Mock troubleshooting there.

**Review by Sudman1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/227)* status: 17 of 21 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[CHANGELOG.md, line 158 at r1](https://reviewable.io/reviews/dsccommunity/xdnsserver/227#-MWiN5ps4YkLy--rZwWf:-MWitjK9A4ct4hDE-hz5:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/9330d4d5a38224e8429a4283a0b4e4b6b95111fb/CHANGELOG.md#L158)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> - xDnsRecordMx
>   - Replaced with class-based implementation, DnsRecordMx
> ```

Can we revert the removal of the old resource and instead add a deprecated message under `### Deprecated`. Let's remove the old one in the next release (as DnsServerDsc). I will create an issue to track the removal.

**Note! You just need to revert the resource code in `xDnsRecord` folder. Let's delete the examples, unit- and integration tests in this PR.**
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/227#-:-MWivC57EL-bsU-ABtYu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sudman1)

**Pull request merged**
