### PR TITLE
DnsServerEDns: New resource proposal

### LINKED ISSUE #194: DnsServerEDns: New resource proposal
### Description
Suggest adding a new resource that changes DNS server EDNS settings. Using the commands [`Get-DnsServerEDns`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserveredns) and [`Set-DnsServerEDns`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/set-dnsserveredns).

### Proposed properties
 - **`DnsServer` <Key, String>** - The host name of the DNS server to change, or use `'localhost'` for the current node.
 - **`EnableProbes` <Write, Boolean>** - Specifies whether to enable the server to probe other servers to determine whether they support EDNS.
 - **`CacheTimeout` <Write, String>** - Specifies the number of seconds that the DNS server caches EDNS information. The default value is 604,800 seconds (one week).
 - **`EnableReception` <Write, Boolean>** - Specifies whether the DNS server accepts queries that contain an EDNS record.

### Special considerations or limitations
The parameter `CacheTimeout` is of the type `[String]` that should be converted to `[TimeSpan]` similar to the `TTL` parameter here:
https://github.com/dsccommunity/xDnsServer/blob/dbcdb067ce905e7c3fc5f74d1ad787c3166f33ba/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L200-L203

The parameters `EnableProbes` and `CacheTimeout` replaces the properties `EnableEDnsProbes` and `EDnsCacheTimeout` in the resource **xDnsServerSetting**, To avoid ping-pong behavior those properties should be removed from the resource **xDnsServerSetting** once this issue is resolved.

### PR DESCRIPTION
**Pull request by johlju**
### Pull Request (PR) description
- xDnsServer
  - Added new resource
    - _DnsServerEDns_ - resource to enforce extension mechanisms for DNS
      (EDNS) settings (issue #194).
  - Added new private function `Assert-TimeSpan` to help assert that a value
    provided in a resource can be converted to a `[System.TimeSpan]` and
    optionally evaluates so it is not below a minium value or over a maximum
    value.

### This Pull Request (PR) fixes the following issues

- Fixes #194

### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/224)

### CODE REVIEW

**Comment by johlju** [comment]
@Sudman1 if you have some time then please review this. It is a big PR.

**Review by Sudman1 — COMMENTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/224)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[source/Classes/003.DnsServerEDns.ps1, line 44 at r1](https://reviewable.io/reviews/dsccommunity/xdnsserver/224#-MWiwRJy-EqGIPeAy0hn:-MWiwRJz1HdmIe_eHdoY:bm4d3mx) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/1a46017e76aa49c92c353393f98c209054c95314/source/Classes/003.DnsServerEDns.ps1#L44)):*
> ```PowerShell
>     $EnableReception
> 
>     [DnsServerEDns] Get()
> ```

This should not impact this PR, but I'd love to have a discussion with regards to how we handle inheritance in a consistent way moving forward because there are some nuanced differences in how you have implemented it vs. how I have with the records.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/224)* status: all files reviewed, 1 unresolved discussion (waiting on @Sudman1)

___
*[source/Classes/003.DnsServerEDns.ps1, line 44 at r1](https://reviewable.io/reviews/dsccommunity/xdnsserver/224#-MWiwRJy-EqGIPeAy0hn:-MWj38ew6rWZ7ppkr53q:b-36gjod) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/1a46017e76aa49c92c353393f98c209054c95314/source/Classes/003.DnsServerEDns.ps1#L44)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

This should not impact this PR, but I'd love to have a discussion with regards to how we handle inheritance in a consistent way moving forward because there are some nuanced differences in how you have implemented it vs. how I have with the records.
</blockquote></details>

Yep, please open an issue to discuss it. What you see need to change. 

I started to look at merging the recursive localization into private functions that will be part of my next PR. It still won't change DnsRecordBase in any way as we need to do controlled in a separate PR. I focus at getting in resources that help fixing the my main focus, fixing xDnsServerSetting.

**Comment by johlju** [comment]
@Sudman1 thank you!

**Pull request merged**
